### ISSUE TITLE
can't download with Vid_ID

### ISSUE THREAD

**Issue by rrfqi** [PatrickL546/Hydrax-Abyss.to-DownloadHelper-Python#15]
how do I fix this error?

```
[Turbo Mode]
If download slows down, try restarting the program

To download multiple videos at once, separate Vid_ID with space

Enter Vid_ID: XEzYNcHnd

Getting Vid_ID text

Traceback (most recent call last):
  File "/content/Hydrax-Abyss.to-DownloadHelper-Python/Hydrax-Abyss.to-DownloadHelper.py", line 60, in get_turbo_download
    ) = get_data(vid_ID_text)
  File "/content/Hydrax-Abyss.to-DownloadHelper-Python/Hydrax-Abyss.to-DownloadHelper.py", line 503, in get_data
    json = loads(decoded_atob)
  File "/usr/lib/python3.10/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/Hydrax-Abyss.to-DownloadHelper-Python/Hydrax-Abyss.to-DownloadHelper.py", line 742, in <module>
    main()
  File "/content/Hydrax-Abyss.to-DownloadHelper-Python/Hydrax-Abyss.to-DownloadHelper.py", line 722, in main
    turbo_download()
  File "/content/Hydrax-Abyss.to-DownloadHelper-Python/Hydrax-Abyss.to-DownloadHelper.py", line 669, in turbo_download
    get_turbo_download(vid_ID_text)
  File "/content/Hydrax-Abyss.to-DownloadHelper-Python/Hydrax-Abyss.to-DownloadHelper.py", line 209, in get_turbo_download
    {bcolors.FAIL}Error downloading: {vid_ID} - get_turbo_download
UnboundLocalError: local variable 'vid_ID' referenced before assignment
```

**Comment by kukhanh29** [comment]
update new encode

**Comment by rrfqi** [comment]
> update new encode

which part should I update the encode code in the python file?

**Comment by kukhanh29** [comment]
> > update new encode
> 
> which part should I update the encode code in the python file?

Abyss update encode
